import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Copy, Eye } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PortalLayout } from '@/components/PortalLayout';
import { useAuth } from '@/context/AuthContext';
import { formatDate } from '@/data/demoData';

export default function Account() {
  const { user, isAuthenticated } = useAuth(); const navigate = useNavigate(); const [revealed, setRevealed] = useState(false); const [timer, setTimer] = useState(0);
  useEffect(() => { if (!isAuthenticated) navigate('/'); }, [isAuthenticated, navigate]);
  useEffect(() => { if (!revealed) return; if (timer <= 0) { setRevealed(false); return; } const id = window.setTimeout(() => setTimer(timer - 1), 1000); return () => window.clearTimeout(id); }, [revealed, timer]);
  if (!user) return null;
  const reveal = () => { setRevealed(true); setTimer(30); };
  return <PortalLayout><h1 className="font-heading text-4xl text-navy md:text-5xl">Profile</h1><div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl bg-card p-6 shadow-sm"><h2 className="font-heading text-2xl text-navy">Personal details</h2><div className="mt-5 grid gap-4"><Field label="Name" value={user.name} /><Field label="Email" value={user.email} /><Field label="Phone" value={user.phone} /></div></section><section className="rounded-2xl bg-card p-6 shadow-sm"><h2 className="font-heading text-2xl text-navy">Portal ID</h2><div className="mt-4 flex items-center justify-between rounded-2xl bg-muted/40 p-5"><span className="font-mono text-3xl text-navy">{user.portalId}</span><Button variant="outline" size="sm" onClick={() => navigator.clipboard?.writeText(user.portalId)}><Copy className="h-4 w-4" />Copy</Button></div></section><section className="rounded-2xl bg-card p-6 shadow-sm"><h2 className="font-heading text-2xl text-navy">NHI Number</h2><div className="mt-4 rounded-2xl bg-muted/40 p-5"><p className="font-mono text-2xl text-navy">{revealed ? user.nhi : `${user.nhi.slice(0, 3)} ****`}</p>{revealed ? <div className="mt-4"><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-deep-teal transition-all" style={{ width: `${(timer / 30) * 100}%` }} /></div><p className="mt-2 font-mono text-xs text-muted-foreground">{timer}s</p></div> : <Button className="mt-4" variant="outline" onClick={reveal}><Eye className="h-4 w-4" />View NHI Number</Button>}</div></section><section className="rounded-2xl bg-card p-6 shadow-sm"><h2 className="font-heading text-2xl text-navy">Notification preferences</h2><label className="mt-5 flex items-center justify-between font-body"><span>SMS reminders</span><input type="checkbox" defaultChecked className="h-5 w-5 accent-deep-teal" /></label><label className="mt-4 flex items-center justify-between font-body"><span>Email order updates</span><input type="checkbox" defaultChecked className="h-5 w-5 accent-deep-teal" /></label></section></div><section className="mt-6 rounded-2xl bg-card p-6 shadow-sm"><h2 className="font-heading text-2xl text-navy">Orders</h2><div className="mt-4 divide-y divide-muted/70">{user.orders.map((order) => <div key={order.id} className="grid gap-2 py-3 font-body text-sm md:grid-cols-[150px_1fr_120px]"><span className="font-mono text-muted-foreground">{formatDate(order.date)}</span><span>{order.items}</span><span className="capitalize text-deep-teal">{order.status}</span></div>)}</div></section></PortalLayout>;
}
function Field({ label, value }: { label: string; value: string }) { return <label><span className="font-mono text-[11px] uppercase tracking-wider text-muted-foreground">{label}</span><input className="mt-1 w-full rounded-full bg-muted/40 px-4 py-3 font-body" defaultValue={value} /></label>; }
