import { useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { PortalLayout } from '@/components/PortalLayout';
import { useAuth } from '@/context/AuthContext';
import { useCart } from '@/context/CartContext';

export default function Checkout() {
  const { user, isAuthenticated } = useAuth(); const { items, totalPaid } = useCart(); const navigate = useNavigate();
  useEffect(() => { if (!isAuthenticated) navigate('/'); }, [isAuthenticated, navigate]);
  if (!user) return null;
  const funded = items.filter((i) => i.isEntitlement); const paid = items.filter((i) => !i.isEntitlement);
  return <PortalLayout><h1 className="font-heading text-4xl text-navy md:text-5xl">Checkout</h1><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-6">{funded.length > 0 && <section className="rounded-2xl bg-card p-6 shadow-sm"><h2 className="font-heading text-2xl text-navy">Your Funded Supplies</h2><p className="font-body text-sm text-muted-foreground">Covered by your CPAP scheme</p><div className="mt-4 space-y-2">{funded.map((item) => <div key={item.id} className="flex justify-between font-body"><span>{item.name}</span><span className="text-seafoam-foreground">✅ Covered — $0.00</span></div>)}</div></section>}<section className="rounded-2xl bg-card p-6 shadow-sm"><h2 className="font-heading text-2xl text-navy">Patient Price (10% off)</h2><p className="font-body text-sm text-muted-foreground">Your Midland patient discount</p><div className="mt-4 space-y-2">{paid.length ? paid.map((item) => <div key={item.id} className="flex justify-between gap-3 font-body"><span>{item.name} <span className="ml-2 rounded-full bg-seafoam/15 px-2 py-0.5 font-mono text-[10px] text-seafoam-foreground">Patient Price</span></span><span className="font-mono">${(item.price * item.quantity).toFixed(2)}</span></div>) : <p className="font-body text-sm text-muted-foreground">No patient price items.</p>}</div></section><section className="rounded-2xl bg-card p-6 shadow-sm"><h2 className="font-heading text-2xl text-navy">Delivery details</h2><div className="mt-4 rounded-2xl bg-deep-teal-pale p-4 font-body text-sm text-foreground">Midland Sleep collects delivery details to process this request under the Health Information Privacy Code 2020.</div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Name" value={user.name} /><Field label="Email" value={user.email} /><Field label="Phone" value={user.phone} /><Field label="Address" value={`${user.address}, ${user.suburb}`} /><Field label="City" value={user.city} /><Field label="Postcode" value={user.postcode} /></div></section></div><aside className="h-fit rounded-2xl bg-card p-6 shadow-sm"><h2 className="font-heading text-2xl text-navy">Summary</h2><div className="mt-5 space-y-3 font-body"><div className="flex justify-between"><span>Funded supplies</span><span>$0.00</span></div><div className="flex justify-between text-lg"><span>You pay today</span><span className="font-mono text-navy">${totalPaid.toFixed(2)}</span></div></div><Button className="mt-6 w-full" size="lg" onClick={() => navigate('/portal/checkout/success')}>{paid.length ? 'Pay by Card →' : 'Submit Request →'}</Button>{paid.length > 0 && <p className="mt-3 text-center font-body text-xs text-muted-foreground">Stripe Elements placeholder for production.</p>}</aside></div></PortalLayout>;
}
function Field({ label, value }: { label: string; value: string }) { return <label><span className="font-mono text-[11px] uppercase tracking-wider text-muted-foreground">{label}</span><input className="mt-1 w-full rounded-full bg-muted/40 px-4 py-3 font-body" defaultValue={value} /></label>; }
