import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { PortalLayout } from '@/components/PortalLayout';
import { useAuth } from '@/context/AuthContext';
import { compatibleSupplies, formatDate } from '@/data/demoData';

export default function Reorder() {
  const { user, isAuthenticated } = useAuth(); const navigate = useNavigate(); const [sent, setSent] = useState(false);
  useEffect(() => { if (!isAuthenticated) navigate('/'); }, [isAuthenticated, navigate]);
  if (!user) return null;
  if (sent) return <PortalLayout><section className="rounded-2xl bg-card p-8 text-center shadow-sm"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-seafoam/15 text-3xl text-seafoam">✓</div><h1 className="mt-5 font-heading text-4xl text-navy">Your request has been received.</h1><p className="mt-2 font-body text-muted-foreground">We'll review and dispatch shortly.</p><Button className="mt-6" onClick={() => navigate('/portal/dashboard')}>Back to Dashboard →</Button></section></PortalLayout>;
  return <PortalLayout><h1 className="font-heading text-4xl text-navy md:text-5xl">Request Supplies</h1><p className="mt-2 font-body text-muted-foreground">Compatible with {user.mask.name} — {user.mask.size}</p><div className="mt-8 grid gap-4">{compatibleSupplies.map((item) => { const future = item.status === 'future' || user.eligibilityStatus === 'not_eligible'; return <section key={item.id} className="rounded-2xl bg-card p-5 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="font-body text-lg font-medium text-foreground">{item.name}</h2><p className="font-body text-sm text-muted-foreground">Quantity <select className="ml-2 rounded-full bg-muted px-3 py-1"><option>1</option><option>2</option></select></p></div><span className={`rounded-full px-3 py-1 font-mono text-xs ${future ? 'bg-muted text-muted-foreground' : item.status === 'early' ? 'bg-amber/15 text-amber-foreground' : 'bg-seafoam/15 text-seafoam-foreground'}`}>{future ? `⏳ From ${formatDate(user.nextEligibleDate)}` : item.status === 'early' ? '⚠️ Early request — clinic may review' : '✅ Available now'}</span></div></section>; })}</div><section className="mt-6 rounded-2xl bg-card p-6 shadow-sm"><h2 className="font-heading text-2xl text-navy">Delivery address</h2><input className="mt-4 w-full rounded-full bg-muted/40 px-4 py-3 font-body" defaultValue={`${user.address}, ${user.suburb}, ${user.city} ${user.postcode}`} /><label className="mt-5 flex items-center gap-3 font-body text-sm"><input type="checkbox" className="h-4 w-4 accent-deep-teal" />For my personal CPAP therapy</label><Button className="mt-5" onClick={() => setSent(true)} disabled={user.eligibilityStatus === 'not_eligible'}>Submit Request →</Button></section><Link to="/portal/shop" className="mt-5 block text-center font-body text-sm text-deep-teal">Looking for something else? Browse the shop →</Link></PortalLayout>;
}
